// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafiCodeAPI.Modal.Modal;

namespace SafiCodeAPI.Modal.Migrations
{
    [DbContext(typeof(SafiCodeContext))]
    [Migration("20210428162834_TblUsers")]
    partial class TblUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SafiCodeAPI.Modal.Modal.TblUserContacts", b =>
                {
                    b.Property<long>("UserContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserContactID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(250);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnName("EmailID")
                        .HasMaxLength(250);

                    b.Property<bool?>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("MainPhone")
                        .HasMaxLength(20);

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(20);

                    b.Property<long?>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title");

                    b.Property<long>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("UserContactId");

                    b.ToTable("Tbl_User_Contacts");
                });

            modelBuilder.Entity("SafiCodeAPI.Modal.Modal.TblUsers", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .HasMaxLength(300);

                    b.Property<string>("City")
                        .HasMaxLength(200);

                    b.Property<int?>("ClientType");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(400);

                    b.Property<long?>("CountryId")
                        .HasColumnName("CountryID");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(200);

                    b.Property<string>("EmailId")
                        .HasColumnName("EmailID")
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .HasMaxLength(400);

                    b.Property<string>("HouseOfficeNo")
                        .HasMaxLength(200);

                    b.Property<string>("Industry")
                        .HasMaxLength(500);

                    b.Property<bool?>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<bool?>("IstermsCondition")
                        .HasColumnName("ISTermsCondition");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20);

                    b.Property<long?>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes");

                    b.Property<string>("Password")
                        .HasMaxLength(200);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(200);

                    b.Property<long?>("UserTypeId")
                        .HasColumnName("UserTypeID");

                    b.Property<string>("Zip")
                        .HasMaxLength(20);

                    b.HasKey("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("tbl_Users");
                });

            modelBuilder.Entity("SafiCodeAPI.Modal.Modal.TblUserType", b =>
                {
                    b.Property<long>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description");

                    b.Property<bool?>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserType")
                        .HasMaxLength(200);

                    b.HasKey("UserTypeId");

                    b.ToTable("tbl_UserType");
                });

            modelBuilder.Entity("SafiCodeAPI.Modal.Modal.TblUsers", b =>
                {
                    b.HasOne("SafiCodeAPI.Modal.Modal.TblUserType", "UserType")
                        .WithMany("TblUsers")
                        .HasForeignKey("UserTypeId")
                        .HasConstraintName("FK_tbl_Users_tbl_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
